clear all; close all; clc;

%% Inisialisasi
    Coeff = 55; %coefficient to keep on CRP
    fn = 15; %frame to keep on features
    nCodebook = 64; %Default Codebook
    st_tr = xlsread('Fold_train.xlsx');
    st_tst = xlsread('Fold_valid.xlsx');
    folder_tr = {'E:\University\Semester 8\TA SUKSES\Program\Dataset\f1\train'....
                ,'E:\University\Semester 8\TA SUKSES\Program\Dataset\f2\train'....
                ,'E:\University\Semester 8\TA SUKSES\Program\Dataset\f3\train'....
                ,'E:\University\Semester 8\TA SUKSES\Program\Dataset\f4\train'....
                ,'E:\University\Semester 8\TA SUKSES\Program\Dataset\f5\train'....
                ,'E:\University\Semester 8\TA SUKSES\Program\Dataset\f6\train'....
                ,'E:\University\Semester 8\TA SUKSES\Program\Dataset\f7\train'....
                ,'E:\University\Semester 8\TA SUKSES\Program\Dataset\f8\train'....
                ,'E:\University\Semester 8\TA SUKSES\Program\Dataset\f9\train'....
                ,'E:\University\Semester 8\TA SUKSES\Program\Dataset\f10\train'}; 
    folder_tst = {'E:\University\Semester 8\TA SUKSES\Program\Dataset\f1\validation'....
                ,'E:\University\Semester 8\TA SUKSES\Program\Dataset\f2\validation'....
                ,'E:\University\Semester 8\TA SUKSES\Program\Dataset\f3\validation'....
                ,'E:\University\Semester 8\TA SUKSES\Program\Dataset\f4\validation'....
                ,'E:\University\Semester 8\TA SUKSES\Program\Dataset\f5\validation'....
                ,'E:\University\Semester 8\TA SUKSES\Program\Dataset\f6\validation'....
                ,'E:\University\Semester 8\TA SUKSES\Program\Dataset\f7\validation'....
                ,'E:\University\Semester 8\TA SUKSES\Program\Dataset\f8\validation'....
                ,'E:\University\Semester 8\TA SUKSES\Program\Dataset\f9\validation'....
                ,'E:\University\Semester 8\TA SUKSES\Program\Dataset\f10\validation'}; 
    
    for i=1:length(folder_tr) 
        fold_tr = folder_tr{i};
        fold_tst = folder_tst{i};
        
        Chromas = Extract_chromas(fold_tr,Coeff,fn);
        
        [Codeindex] = Generate_Codeword(Chromas,nCodebook);
        
        [Codebook_tr] = Generate_Codebook_Coeff(fold_tr,Coeff,fn,Codeindex); %Codebook for train data
        [Codebook_tst] = Generate_Codebook_Coeff(fold_tst,Coeff,fn,Codeindex); %Codebook for test data
        
    %% Klasifikasi
    [likelystates_tr, likelystates_tst] = KlasifikasiHMM(Codebook_tr,Codebook_tst,st_tr);
    
    accuracy(i,1)= sum(st_tr==likelystates_tr)/length(st_tr);
    accuracy(i,2)= sum(st_tst==likelystates_tst)/length(st_tst);
    end
    
    %save('classfication_fold2','accuracy');
    %load('classfication_fold2');
    sum1 = sum(accuracy(:,1))/length(accuracy(:,1))
    sum2 = sum(accuracy(:,2))/length(accuracy(:,2))
    